blocks:
- AIR
- ANVIL  
- BANNER 
- BEACON 
- BEDROCK 
- BIRCH_WOOD_STAIRS 
- BLACK_SHULKER_BOX 
- BLUE_SHULKER_BOX 
- BONE_BLOCK 
- BOOKSHELF 
- BRICK 
- BRICK_STAIRS 
- BROWN_SHULKER_BOX 
- CACTUS 
- CAULDRON 
- CHEST 
- CLAY   
- COAL_BLOCK 
- COAL_ORE 
- COBBLE_WALL 
- COBBLESTONE 
- COBBLESTONE_STAIRS 
- CYAN_SHULKER_BOX 
- DARK_OAK_STAIRS
- DIAMOND_BLOCK
- DIAMOND_ORE   
- DIRT 
- DISPENSER 
- DOUBLE_STEP 
- DOUBLE_STONE_SLAB2 
- DROPPER 
- EMERALD_BLOCK 
- EMERALD_ORE 
- ENCHANTMENT_TABLE 
- END_BRICKS 
- ENDER_CHEST 
- ENDER_STONE 
- FURNACE 
- GLOWSTONE 
- GOLD_BLOCK 
- GOLD_ORE 
- GRASS 
- GRASS_PATH 
- GRAVEL 
- GRAY_SHULKER_BOX 
- GREEN_SHULKER_BOX 
- HARD_CLAY 
- HAY_BLOCK 
- HOPPER 
- ICE 
- IRON_BLOCK 
- IRON_ORE 
- JACK_O_LANTERN 
- JUKEBOX 
- JUNGLE_WOOD_STAIRS 
- LAPIS_BLOCK 
- LAPIS_ORE 
- LEAVES 
- LEAVES_2 
- LIGHT_BLUE_SHULKER_BOX 
- LIME_SHULKER_BOX 
- LOG 
- LOG_2 
- MAGENTA_SHULKER_BOX 
- MELON_BLOCK 
- MOB_SPAWNER 
- MOSSY_COBBLESTONE 
- NETHER_BRICK_ITEM 
- NETHER_BRICK_STAIRS 
- NETHERRACK 
- NOTE_BLOCK 
- OBSERVER 
- OBSIDIAN 
- ORANGE_SHULKER_BOX 
- PACKED_ICE 
- PINK_SHULKER_BOX 
- PISTON_BASE 
- PISTON_STICKY_BASE 
- PRISMARINE 
- PUMPKIN 
- PURPLE_SHULKER_BOX 
- PURPUR_BLOCK 
- PURPUR_DOUBLE_SLAB 
- PURPUR_PILLAR 
- PURPUR_SLAB 
- PURPUR_STAIRS 
- QUARTZ_BLOCK 
- QUARTZ_ORE 
- QUARTZ_STAIRS 
- RECORD_10 
- RECORD_11 
- RECORD_12 
- RECORD_3 
- RECORD_4 
- RECORD_5 
- RECORD_6 
- RECORD_7 
- RECORD_8 
- RECORD_9 
- RED_MUSHROOM 
- RED_NETHER_BRICK 
- RED_SANDSTONE 
- RED_SANDSTONE_STAIRS 
- RED_SHULKER_BOX 
- REDSTONE_BLOCK 
- REDSTONE_LAMP_OFF 
- REDSTONE_LAMP_ON 
- REDSTONE_ORE 
- SAND 
- SANDSTONE 
- SANDSTONE_STAIRS 
- SEA_LANTERN 
- SILVER_SHULKER_BOX 
- SLIME_BLOCK 
- SMOOTH_BRICK 
- SMOOTH_STAIRS 
- SNOW_BLOCK 
- SOUL_SAND 
- SPONGE 
- SPRUCE_WOOD_STAIRS 
- STAINED_CLAY 
- STAINED_GLASS 
- STAINED_GLASS_PANE 
- STANDING_BANNER 
- STATIONARY_LAVA 
- STATIONARY_WATER 
- STEP 
- STONE 
- STONE_SLAB2 
- THIN_GLASS 
- TNT 
- TRAPPED_CHEST 
- WHITE_SHULKER_BOX 
- WOOD 
- WOOD_DOUBLE_STEP 
- WOOD_STAIRS 
- WOOD_STEP 
- WOOL 
- WORKBENCH 
- YELLOW_SHULKER_BOX 
