blocks:
  blockhat:
    - ACACIA_LEAVES
    - ACACIA_LOG
    - ACACIA_PLANKS
    - ACACIA_SLAB
    - ACACIA_STAIRS
    - ACACIA_WOOD
    - AMETHYST_BLOCK
    - ANCIENT_DEBRIS
    - ANDESITE
    - ANDESITE_SLAB
    - ANDESITE_STAIRS
    - ANVIL
    - AZALEA
    - AZALEA_LEAVES
    - BARREL
    - BARRIER
    - BASALT
    - BEACON
    - BEDROCK
    - BEE_NEST
    - BEEHIVE
    - BIG_DRIPLEAF
    - BIRCH_LEAVES
    - BIRCH_LOG
    - BIRCH_PLANKS
    - BIRCH_SLAB
    - BIRCH_STAIRS
    - BIRCH_WOOD
    - BLACK_BANNER
    - BLACK_CONCRETE
    - BLACK_CONCRETE_POWDER
    - BLACK_GLAZED_TERRACOTTA
    - BLACK_STAINED_GLASS
    - BLACK_TERRACOTTA
    - BLACK_WOOL
    - BLACKSTONE
    - BLACKSTONE_SLAB
    - BLACKSTONE_STAIRS
    - BLAST_FURNACE
    - BLUE_BANNER
    - BLUE_CONCRETE
    - BLUE_CONCRETE_POWDER
    - BLUE_GLAZED_TERRACOTTA
    - BLUE_ICE
    - BLUE_STAINED_GLASS
    - BLUE_TERRACOTTA
    - BLUE_WOOL
    - BONE_BLOCK
    - BOOKSHELF
    - BRAIN_CORAL_BLOCK
    - BRICK
    - BRICK_SLAB
    - BRICK_STAIRS
    - BRICK_WALL
    - BROWN_BANNER
    - BROWN_CONCRETE
    - BROWN_CONCRETE_POWDER
    - BROWN_GLAZED_TERRACOTTA
    - BROWN_MUSHROOM_BLOCK
    - BROWN_STAINED_GLASS
    - BROWN_TERRACOTTA
    - BROWN_WOOL
    - BUBBLE_CORAL_BLOCK
    - BUDDING_AMETHYST
    - CACTUS
    - CALCITE
    - CARTOGRAPHY_TABLE
    - CARVED_PUMPKIN
    - CAULDRON
    - CHEST
    - CHIPPED_ANVIL
    - CHISELED_DEEPSLATE
    - CHISELED_NETHER_BRICKS
    - CHISELED_POLISHED_BLACKSTONE
    - CHISELED_QUARTZ_BLOCK
    - CHISELED_RED_SANDSTONE
    - CHISELED_SANDSTONE
    - CHISELED_STONE_BRICKS
    - CLAY
    - COAL_BLOCK
    - COAL_ORE
    - COARSE_DIRT
    - COBBLED_DEEPSLATE
    - COBBLED_DEEPSLATE_SLAB
    - COBBLED_DEEPSLATE_STAIRS
    - COBBLED_DEEPSLATE_WALL
    - COBBLESTONE
    - COBBLESTONE_SLAB
    - COBBLESTONE_STAIRS
    - COBBLESTONE_WALL
    - COMPOSTER
    - COPPER_BLOCK
    - COPPER_ORE
    - CRACKED_DEEPSLATE_BRICKS
    - CRACKED_DEEPSLATE_TILES
    - CRACKED_NETHER_BRICKS
    - CRACKED_POLISHED_BLACKSTONE_BRICKS
    - CRACKED_STONE_BRICKS
    - CRAFTING_TABLE
    - CRIMSON_NYLIUM
    - CRIMSON_PLANKS
    - CRIMSON_SLAB
    - CRIMSON_STAIRS
    - CRIMSON_STEM
    - CRYING_OBSIDIAN
    - CUT_COPPER
    - CUT_COPPER_SLAB
    - CUT_COPPER_STAIRS
    - CUT_RED_SANDSTONE
    - CUT_RED_SANDSTONE_SLAB
    - CUT_SANDSTONE
    - CUT_SANDSTONE_SLAB
    - CYAN_BANNER
    - CYAN_CONCRETE
    - CYAN_CONCRETE_POWDER
    - CYAN_GLAZED_TERRACOTTA
    - CYAN_STAINED_GLASS
    - CYAN_TERRACOTTA
    - CYAN_WOOL
    - DAMAGED_ANVIL
    - DARK_OAK_LEAVES
    - DARK_OAK_LOG
    - DARK_OAK_PLANKS
    - DARK_OAK_SLAB
    - DARK_OAK_STAIRS
    - DARK_OAK_WOOD
    - DARK_PRISMARINE
    - DARK_PRISMARINE_SLAB
    - DARK_PRISMARINE_STAIRS
    - DEAD_BRAIN_CORAL_BLOCK
    - DEAD_BUBBLE_CORAL_BLOCK
    - DEAD_FIRE_CORAL_BLOCK
    - DEAD_HORN_CORAL_BLOCK
    - DEAD_TUBE_CORAL_BLOCK
    - DEEPSLATE
    - DEEPSLATE_BRICK_SLAB
    - DEEPSLATE_BRICK_STAIRS
    - DEEPSLATE_BRICK_WALL
    - DEEPSLATE_BRICKS
    - DEEPSLATE_COAL_ORE
    - DEEPSLATE_COPPER_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DEEPSLATE_EMERALD_ORE
    - DEEPSLATE_GOLD_ORE
    - DEEPSLATE_IRON_ORE
    - DEEPSLATE_LAPIS_ORE
    - DEEPSLATE_REDSTONE_ORE
    - DEEPSLATE_TILE_SLAB
    - DEEPSLATE_TILE_STAIRS
    - DEEPSLATE_TILE_WALL
    - DEEPSLATE_TILES
    - DIAMOND_BLOCK
    - DIAMOND_ORE
    - DIORITE
    - DIORITE_SLAB
    - DIRT
    - DISPENSER
    - DRIED_KELP_BLOCK
    - DRIPSTONE_BLOCK
    - DROPPER
    - EMERALD_BLOCK
    - EMERALD_ORE
    - ENCHANTING_TABLE
    - END_STONE
    - END_STONE_BRICK_SLAB
    - END_STONE_BRICK_STAIRS
    - END_STONE_BRICKS
    - ENDER_CHEST
    - EXPOSED_COPPER
    - EXPOSED_CUT_COPPER
    - EXPOSED_CUT_COPPER_SLAB
    - EXPOSED_CUT_COPPER_STAIRS
    - FIRE_CORAL_BLOCK
    - FLETCHING_TABLE
    - FLOWERING_AZALEA
    - FLOWERING_AZALEA_LEAVES
    - FURNACE
    - GILDED_BLACKSTONE
    - GLASS
    - GLOWSTONE
    - GOLD_BLOCK
    - GOLD_ORE
    - GRANITE
    - GRANITE_SLAB
    - GRANITE_STAIRS
    - GRASS_BLOCK
    - GRAVEL
    - GRAY_BANNER
    - GRAY_CONCRETE
    - GRAY_CONCRETE_POWDER
    - GRAY_GLAZED_TERRACOTTA
    - GRAY_STAINED_GLASS
    - GRAY_TERRACOTTA
    - GRAY_WOOL
    - GREEN_BANNER
    - GREEN_CONCRETE
    - GREEN_CONCRETE_POWDER
    - GREEN_GLAZED_TERRACOTTA
    - GREEN_STAINED_GLASS
    - GREEN_TERRACOTTA
    - GREEN_WOOL
    - GRINDSTONE
    - HAY_BLOCK
    - HONEY_BLOCK
    - HONEYCOMB_BLOCK
    - HOPPER
    - HORN_CORAL_BLOCK
    - ICE
    - IRON_BLOCK
    - IRON_ORE
    - JACK_O_LANTERN
    - JIGSAW
    - JUKEBOX
    - JUNGLE_LEAVES
    - JUNGLE_LOG
    - JUNGLE_PLANKS
    - JUNGLE_SLAB
    - JUNGLE_STAIRS
    - JUNGLE_WOOD
    - LAPIS_BLOCK
    - LAPIS_ORE
    - LIGHT_BLUE_BANNER
    - LIGHT_BLUE_CONCRETE
    - LIGHT_BLUE_CONCRETE_POWDER
    - LIGHT_BLUE_GLAZED_TERRACOTTA
    - LIGHT_BLUE_STAINED_GLASS
    - LIGHT_BLUE_TERRACOTTA
    - LIGHT_BLUE_WOOL
    - LIGHT_GRAY_BANNER
    - LIGHT_GRAY_CONCRETE
    - LIGHT_GRAY_CONCRETE_POWDER
    - LIGHT_GRAY_GLAZED_TERRACOTTA
    - LIGHT_GRAY_STAINED_GLASS
    - LIGHT_GRAY_TERRACOTTA
    - LIGHT_GRAY_WOOL
    - LIGHTNING_ROD
    - LIME_BANNER
    - LIME_CONCRETE
    - LIME_CONCRETE_POWDER
    - LIME_GLAZED_TERRACOTTA
    - LIME_STAINED_GLASS
    - LIME_TERRACOTTA
    - LIME_WOOL
    - LODESTONE
    - LOOM
    - MAGENTA_BANNER
    - MAGENTA_CONCRETE
    - MAGENTA_CONCRETE_POWDER
    - MAGENTA_GLAZED_TERRACOTTA
    - MAGENTA_STAINED_GLASS
    - MAGENTA_TERRACOTTA
    - MAGENTA_WOOL
    - MAGMA_BLOCK
    - MELON
    - MOSS_BLOCK
    - MOSSY_COBBLESTONE
    - MOSSY_COBBLESTONE_SLAB
    - MOSSY_COBBLESTONE_STAIRS
    - MOSSY_STONE_BRICK_SLAB
    - MOSSY_STONE_BRICK_STAIRS
    - MOSSY_STONE_BRICKS
    - MUSHROOM_STEM
    - MUSIC_DISC_11
    - MUSIC_DISC_13
    - MUSIC_DISC_BLOCKS
    - MUSIC_DISC_CAT
    - MUSIC_DISC_CHIRP
    - MUSIC_DISC_FAR
    - MUSIC_DISC_MALL
    - MUSIC_DISC_MELLOHI
    - MUSIC_DISC_PIGSTEP
    - MUSIC_DISC_STAL
    - MUSIC_DISC_STRAD
    - MUSIC_DISC_WAIT
    - MUSIC_DISC_WARD
    - MYCELIUM
    - NETHER_BRICK
    - NETHER_BRICK_FENCE
    - NETHER_BRICK_SLAB
    - NETHER_BRICK_STAIRS
    - NETHER_BRICK_WALL
    - NETHER_GOLD_ORE
    - NETHER_QUARTZ_ORE
    - NETHER_WART_BLOCK
    - NETHERITE_BLOCK
    - NETHERRACK
    - NOTE_BLOCK
    - OAK_LEAVES
    - OAK_LOG
    - OAK_PLANKS
    - OAK_SLAB
    - OAK_STAIRS
    - OAK_WOOD
    - OBSERVER
    - OBSIDIAN
    - ORANGE_BANNER
    - ORANGE_CONCRETE
    - ORANGE_CONCRETE_POWDER
    - ORANGE_GLAZED_TERRACOTTA
    - ORANGE_STAINED_GLASS
    - ORANGE_TERRACOTTA
    - ORANGE_WOOL
    - OXIDIZED_COPPER
    - OXIDIZED_COPPER_SLAB
    - OXIDIZED_COPPER_STAIRS
    - PACKED_ICE
    - PETRIFIED_OAK_SLAB
    - PINK_BANNER
    - PINK_CONCRETE
    - PINK_CONCRETE_POWDER
    - PINK_GLAZED_TERRACOTTA
    - PINK_STAINED_GLASS
    - PINK_TERRACOTTA
    - PINK_WOOL
    - PISTON
    - PODZOL
    - POLISHED_ANDESITE
    - POLISHED_ANDESITE_SLAB
    - POLISHED_ANDESITE_STAIRS
    - POLISHED_BASALT
    - POLISHED_BLACKSTONE
    - POLISHED_BLACKSTONE_BRICK_SLAB
    - POLISHED_BLACKSTONE_BRICK_STAIRS
    - POLISHED_BLACKSTONE_BRICKS
    - POLISHED_BLACKSTONE_SLAB
    - POLISHED_BLACKSTONE_STAIRS
    - POLISHED_DEEPSLATE
    - POLISHED_DEEPSLATE_SLAB
    - POLISHED_DEEPSLATE_STAIRS
    - POLISHED_DEEPSLATE_WALL
    - POLISHED_DIORITE
    - POLISHED_DIORITE_SLAB
    - POLISHED_DIORITE_STAIRS
    - POLISHED_GRANITE
    - POLISHED_GRANITE_SLAB
    - POLISHED_GRANITE_STAIRS
    - PRISMARINE
    - PRISMARINE_BRICK_SLAB
    - PRISMARINE_BRICK_STAIRS
    - PRISMARINE_BRICKS
    - PRISMARINE_SLAB
    - PRISMARINE_STAIRS
    - PUMPKIN
    - PURPLE_BANNER
    - PURPLE_CONCRETE
    - PURPLE_CONCRETE_POWDER
    - PURPLE_GLAZED_TERRACOTTA
    - PURPLE_STAINED_GLASS
    - PURPLE_TERRACOTTA
    - PURPLE_WOOL
    - PURPUR_BLOCK
    - PURPUR_PILLAR
    - PURPUR_SLAB
    - PURPUR_STAIRS
    - QUARTZ_BLOCK
    - QUARTZ_BRICKS
    - QUARTZ_PILLAR
    - QUARTZ_SLAB
    - QUARTZ_STAIRS
    - RAW_COPPER_BLOCK
    - RAW_GOLD_BLOCK
    - RAW_IRON_BLOCK
    - RED_BANNER
    - RED_CONCRETE
    - RED_CONCRETE_POWDER
    - RED_GLAZED_TERRACOTTA
    - RED_MUSHROOM_BLOCK
    - RED_NETHER_BRICK_SLAB
    - RED_NETHER_BRICK_STAIRS
    - RED_NETHER_BRICKS
    - RED_SAND
    - RED_SANDSTONE
    - RED_SANDSTONE_SLAB
    - RED_SANDSTONE_STAIRS
    - RED_STAINED_GLASS
    - RED_TERRACOTTA
    - RED_WOOL
    - REDSTONE_BLOCK
    - REDSTONE_LAMP
    - REDSTONE_ORE
    - RESPAWN_ANCHOR
    - ROOTED_DIRT
    - SAND
    - SANDSTONE
    - SANDSTONE_SLAB
    - SANDSTONE_STAIRS
    - SCAFFOLDING
    - SCULK_SENSOR
    - SEA_LANTERN
    - SHROOMLIGHT
    - SLIME_BLOCK
    - SMITHING_TABLE
    - SMOKER
    - SMOOTH_BASALT
    - SMOOTH_QUARTZ
    - SMOOTH_QUARTZ_SLAB
    - SMOOTH_QUARTZ_STAIRS
    - SMOOTH_RED_SANDSTONE
    - SMOOTH_RED_SANDSTONE_SLAB
    - SMOOTH_RED_SANDSTONE_STAIRS
    - SMOOTH_SANDSTONE
    - SMOOTH_SANDSTONE_SLAB
    - SMOOTH_SANDSTONE_STAIRS
    - SMOOTH_STONE
    - SMOOTH_STONE_SLAB
    - SNOW_BLOCK
    - SOUL_SAND
    - SOUL_SOIL
    - SPONGE
    - SPRUCE_LEAVES
    - SPRUCE_LOG
    - SPRUCE_PLANKS
    - SPRUCE_SLAB
    - SPRUCE_STAIRS
    - SPRUCE_WOOD
    - STICKY_PISTON
    - STONE
    - STONE_BRICK_SLAB
    - STONE_BRICK_STAIRS
    - STONE_BRICK_WALL
    - STONE_BRICKS
    - STONE_SLAB
    - STONE_STAIRS
    - STONECUTTER
    - STRIPPED_ACACIA_LOG
    - STRIPPED_ACACIA_WOOD
    - STRIPPED_BIRCH_LOG
    - STRIPPED_BIRCH_WOOD
    - STRIPPED_CRIMSON_HYPHAE
    - STRIPPED_CRIMSON_STEM
    - STRIPPED_DARK_OAK_LOG
    - STRIPPED_DARK_OAK_WOOD
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_JUNGLE_WOOD
    - STRIPPED_OAK_LOG
    - STRIPPED_OAK_WOOD
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_SPRUCE_WOOD
    - STRIPPED_WARPED_HYPHAE
    - STRIPPED_WARPED_STEM
    - TARGET
    - TERRACOTTA
    - TINTED_GLASS
    - TNT
    - TRAPPED_CHEST
    - TUBE_CORAL_BLOCK
    - TUFF
    - WARPED_HYPHAE
    - WARPED_NYLIUM
    - WARPED_PLANKS
    - WARPED_SLAB
    - WARPED_STAIRS
    - WARPED_STEM
    - WARPED_WART_BLOCK
    - WAXED_COPPER_BLOCK
    - WAXED_CUT_COPPER
    - WAXED_CUT_COPPER_SLAB
    - WAXED_CUT_COPPER_STAIRS
    - WAXED_EXPOSED_COPPER
    - WAXED_EXPOSED_CUT_COPPER
    - WAXED_EXPOSED_CUT_COPPER_SLAB
    - WAXED_EXPOSED_CUT_COPPER_STAIRS
    - WAXED_OXIDIZED_COPPER
    - WAXED_OXIDIZED_CUT_COPPER
    - WAXED_OXIDIZED_CUT_COPPER_SLAB
    - WAXED_OXIDIZED_CUT_COPPER_STAIRS
    - WAXED_WEATHERED_COPPER
    - WAXED_WEATHERED_CUT_COPPER
    - WAXED_WEATHERED_CUT_COPPER_SLAB
    - WAXED_WEATHERED_CUT_COPPER_STAIRS
    - WEATHERED_COPPER
    - WEATHERED_CUT_COPPER
    - WEATHERED_CUT_COPPER_SLAB
    - WEATHERED_CUT_COPPER_STAIRS
    - WET_SPONGE
    - WHITE_BANNER
    - WHITE_CONCRETE
    - WHITE_CONCRETE_POWDER
    - WHITE_GLAZED_TERRACOTTA
    - WHITE_STAINED_GLASS
    - WHITE_TERRACOTTA
    - WHITE_WOOL
    - WITCH_SPAWN_EGG
    - YELLOW_BANNER
    - YELLOW_CONCRETE
    - YELLOW_CONCRETE_POWDER
    - YELLOW_GLAZED_TERRACOTTA
    - YELLOW_STAINED_GLASS
    - YELLOW_TERRACOTTA
    - YELLOW_WOOL
    - CRIMSON_HYPHAE
    - OCHRE_FROGLIGHT
    - PEARLESCENT_FROGLIGHT
    - VERDANT_FROGLIGHT
    - MANGROVE_LEAVES
    - MANGROVE_LOG
    - MANGROVE_PLANKS
    - MANGROVE_SLAB
    - MANGROVE_STAIRS
    - MANGROVE_WOOD
    - STRIPPED_MANGROVE_LOG
    - STRIPPED_MANGROVE_WOOD
    - MANGROVE_ROOTS
    - MUDDY_MANGROVE_ROOTS
    - MUD
    - MUD_BRICKS
    - MUD_BRICK_SLAB
    - MUD_BRICK_STAIRS
    - MUD_BRICK_WALL
    - PACKED_MUD
    - REINFORCED_DEEPSLATE
    - SCULK
    - SCULK_CATALYST
    - SCULK_SENSOR
    - SCULK_SHRIEKER
    - BAMBOO_BLOCK
    - BAMBOO_MOSAIC
    - BAMBOO_SLAB
    - BAMBOO_STAIRS
    - BAMBOO_PLANKS
    - BAMBOO_MOSAIC_SLAB
    - BAMBOO_MOSAIC_STAIRS
    - STRIPPED_BAMBOO_BLOCK
    - CALIBRATED_SCULK_SENSOR
    - CHERRY_LEAVES
    - CHERRY_LOG
    - CHERRY_PLANKS
    - CHERRY_SLAB
    - CHERRY_STAIRS
    - CHERRY_WOOD
    - STRIPPED_CHERRY_LOG
    - STRIPPED_CHERRY_WOOD
    - CHISELED_BOOKSHELF
    - SUSPICIOUS_SAND
    - SUSPICIOUS_GRAVEL
  mayflower:
    - DANDELION
    - POPPY
    - BLUE_ORCHID
    - ALLIUM
    - AZURE_BLUET
    - RED_TULIP
    - ORANGE_TULIP
    - WHITE_TULIP
    - PINK_TULIP
    - OXEYE_DAISY
    - CORNFLOWER
    - LILY_OF_THE_VALLEY
    - WITHER_ROSE
    - SUNFLOWER
    - LILAC
    - ROSE_BUSH
    - PEONY
    - SPORE_BLOSSOM
    - PINK_PETALS
    - PITCHER_PLANT
    - TORCHFLOWER